name: Setup Node and pnpm
description: Setup Node.js and pnpm with caching

inputs:
  fetch-depth:
    description: Number of commits to fetch
    required: false
    default: "1"
  registry-url:
    description: Registry URL for npm
    required: false
    default: ""
  ref:
    description: Git ref to checkout
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.ref }}
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm
    - run: pnpm install
      shell: bash
