import { exit } from 'node:process';
import { components } from '@lichess-org/types';
import { msgCommonErrorHelp, sleep, checkTokenScopes } from '../utils/commandHandler.js';
import { getBroadcastRound } from '../utils/getInfoBroadcast.js';
import cl from '../utils/colors.js';
import { pushPGN, loopChecker } from '../utils/pushTools.js';
import { ChildNode, makePgn, PgnNodeData, Game as ChessGame, Node } from 'chessops/pgn';
import { Chess } from 'chessops/chess';
import { parseFen } from 'chessops/fen';
import { parseSan } from 'chessops/san';
import dayjs from 'dayjs';
import duration from 'dayjs/plugin/duration.js';
dayjs.extend(duration);

let lastPGN = '';

// https://1.pool.livechesscloud.com/get/<tournament_id>/tournament.json
export interface Tournament {
  name: string;
  timecontrol?: string;
  // TODO: what rules are there?
  rules: 'STANDARD' | string;
  // TODO: what does this field contain for chess960 games?
  chess960: 'STANDARD' | 'ANY';
  rounds: Array<{
    count: number;
    live: 0 | 1;
  }>;
}

interface Player {
  fname: string | null;
  mname: string | null;
  lname: string | null;
  title: string | null;
  // the FIDE ID, if filled by the organiser. check on ratings.fide.com
  fideid: number | null;
}

export interface Pairing {
  white: Player;
  black: Player;
  result: string;
  live: boolean;
}

// https://1.pool.livechesscloud.com/get/<tournament_id>/round-<round_number>/index.json
export interface Round {
  // TODO: what does this contain when date is there?
  date: null;
  pairings: Array<Pairing>;
}

// https://1.pool.livechesscloud.com/get/<tournament_id>/round-<round_no>/game-<game_no>.json
export interface Game {
  // Looks like https://en.wikipedia.org/wiki/Fischer_random_chess_numbering_scheme
  // although it's also provided for standard games, only needed for chess960.
  chess960: number;
  moves: Array<string>;
}

async function getRound(tournamentId: string, round: number): Promise<Round> {
  return await fetch(`https://1.pool.livechesscloud.com/get/${tournamentId}/round-${round}/index.json`).then(
    res => res.json(),
  );
}

async function getGame(tournamentId: string, round: number, game: number): Promise<Game> {
  return await fetch(
    `https://1.pool.livechesscloud.com/get/${tournamentId}/round-${round}/game-${game}.json`,
  ).then(res => res.json());
}

function getPlayerName(player: Player): string {
  let name = '';
  if (player.fname) name += player.fname;
  if (player.mname) name += ` ${player.mname}`;
  if (player.lname) name += ` ${player.lname}`;
  return name;
}

export const positionToFen = (position: number): string | undefined => {
  const rank8 = positions[position];
  if (rank8) {
    return `${rank8}/pppppppp/8/8/8/8/PPPPPPPP/${rank8.toUpperCase()} w KQkq - 0 1`;
  }
};

const positions = [
  'bbqnnrkr',
  'bqnbnrkr',
  'bqnnrbkr',
  'bqnnrkrb',
  'qbbnnrkr',
  'qnbbnrkr',
  'qnbnrbkr',
  'qnbnrkrb',
  'qbnnbrkr',
  'qnnbbrkr',
  'qnnrbbkr',
  'qnnrbkrb',
  'qbnnrkbr',
  'qnnbrkbr',
  'qnnrkbbr',
  'qnnrkrbb',
  'bbnqnrkr',
  'bnqbnrkr',
  'bnqnrbkr',
  'bnqnrkrb',
  'nbbqnrkr',
  'nqbbnrkr',
  'nqbnrbkr',
  'nqbnrkrb',
  'nbqnbrkr',
  'nqnbbrkr',
  'nqnrbbkr',
  'nqnrbkrb',
  'nbqnrkbr',
  'nqnbrkbr',
  'nqnrkbbr',
  'nqnrkrbb',
  'bbnnqrkr',
  'bnnbqrkr',
  'bnnqrbkr',
  'bnnqrkrb',
  'nbbnqrkr',
  'nnbbqrkr',
  'nnbqrbkr',
  'nnbqrkrb',
  'nbnqbrkr',
  'nnqbbrkr',
  'nnqrbbkr',
  'nnqrbkrb',
  'nbnqrkbr',
  'nnqbrkbr',
  'nnqrkbbr',
  'nnqrkrbb',
  'bbnnrqkr',
  'bnnbrqkr',
  'bnnrqbkr',
  'bnnrqkrb',
  'nbbnrqkr',
  'nnbbrqkr',
  'nnbrqbkr',
  'nnbrqkrb',
  'nbnrbqkr',
  'nnrbbqkr',
  'nnrqbbkr',
  'nnrqbkrb',
  'nbnrqkbr',
  'nnrbqkbr',
  'nnrqkbbr',
  'nnrqkrbb',
  'bbnnrkqr',
  'bnnbrkqr',
  'bnnrkbqr',
  'bnnrkqrb',
  'nbbnrkqr',
  'nnbbrkqr',
  'nnbrkbqr',
  'nnbrkqrb',
  'nbnrbkqr',
  'nnrbbkqr',
  'nnrkbbqr',
  'nnrkbqrb',
  'nbnrkqbr',
  'nnrbkqbr',
  'nnrkqbbr',
  'nnrkqrbb',
  'bbnnrkrq',
  'bnnbrkrq',
  'bnnrkbrq',
  'bnnrkrqb',
  'nbbnrkrq',
  'nnbbrkrq',
  'nnbrkbrq',
  'nnbrkrqb',
  'nbnrbkrq',
  'nnrbbkrq',
  'nnrkbbrq',
  'nnrkbrqb',
  'nbnrkrbq',
  'nnrbkrbq',
  'nnrkrbbq',
  'nnrkrqbb',
  'bbqnrnkr',
  'bqnbrnkr',
  'bqnrnbkr',
  'bqnrnkrb',
  'qbbnrnkr',
  'qnbbrnkr',
  'qnbrnbkr',
  'qnbrnkrb',
  'qbnrbnkr',
  'qnrbbnkr',
  'qnrnbbkr',
  'qnrnbkrb',
  'qbnrnkbr',
  'qnrbnkbr',
  'qnrnkbbr',
  'qnrnkrbb',
  'bbnqrnkr',
  'bnqbrnkr',
  'bnqrnbkr',
  'bnqrnkrb',
  'nbbqrnkr',
  'nqbbrnkr',
  'nqbrnbkr',
  'nqbrnkrb',
  'nbqrbnkr',
  'nqrbbnkr',
  'nqrnbbkr',
  'nqrnbkrb',
  'nbqrnkbr',
  'nqrbnkbr',
  'nqrnkbbr',
  'nqrnkrbb',
  'bbnrqnkr',
  'bnrbqnkr',
  'bnrqnbkr',
  'bnrqnkrb',
  'nbbrqnkr',
  'nrbbqnkr',
  'nrbqnbkr',
  'nrbqnkrb',
  'nbrqbnkr',
  'nrqbbnkr',
  'nrqnbbkr',
  'nrqnbkrb',
  'nbrqnkbr',
  'nrqbnkbr',
  'nrqnkbbr',
  'nrqnkrbb',
  'bbnrnqkr',
  'bnrbnqkr',
  'bnrnqbkr',
  'bnrnqkrb',
  'nbbrnqkr',
  'nrbbnqkr',
  'nrbnqbkr',
  'nrbnqkrb',
  'nbrnbqkr',
  'nrnbbqkr',
  'nrnqbbkr',
  'nrnqbkrb',
  'nbrnqkbr',
  'nrnbqkbr',
  'nrnqkbbr',
  'nrnqkrbb',
  'bbnrnkqr',
  'bnrbnkqr',
  'bnrnkbqr',
  'bnrnkqrb',
  'nbbrnkqr',
  'nrbbnkqr',
  'nrbnkbqr',
  'nrbnkqrb',
  'nbrnbkqr',
  'nrnbbkqr',
  'nrnkbbqr',
  'nrnkbqrb',
  'nbrnkqbr',
  'nrnbkqbr',
  'nrnkqbbr',
  'nrnkqrbb',
  'bbnrnkrq',
  'bnrbnkrq',
  'bnrnkbrq',
  'bnrnkrqb',
  'nbbrnkrq',
  'nrbbnkrq',
  'nrbnkbrq',
  'nrbnkrqb',
  'nbrnbkrq',
  'nrnbbkrq',
  'nrnkbbrq',
  'nrnkbrqb',
  'nbrnkrbq',
  'nrnbkrbq',
  'nrnkrbbq',
  'nrnkrqbb',
  'bbqnrknr',
  'bqnbrknr',
  'bqnrkbnr',
  'bqnrknrb',
  'qbbnrknr',
  'qnbbrknr',
  'qnbrkbnr',
  'qnbrknrb',
  'qbnrbknr',
  'qnrbbknr',
  'qnrkbbnr',
  'qnrkbnrb',
  'qbnrknbr',
  'qnrbknbr',
  'qnrknbbr',
  'qnrknrbb',
  'bbnqrknr',
  'bnqbrknr',
  'bnqrkbnr',
  'bnqrknrb',
  'nbbqrknr',
  'nqbbrknr',
  'nqbrkbnr',
  'nqbrknrb',
  'nbqrbknr',
  'nqrbbknr',
  'nqrkbbnr',
  'nqrkbnrb',
  'nbqrknbr',
  'nqrbknbr',
  'nqrknbbr',
  'nqrknrbb',
  'bbnrqknr',
  'bnrbqknr',
  'bnrqkbnr',
  'bnrqknrb',
  'nbbrqknr',
  'nrbbqknr',
  'nrbqkbnr',
  'nrbqknrb',
  'nbrqbknr',
  'nrqbbknr',
  'nrqkbbnr',
  'nrqkbnrb',
  'nbrqknbr',
  'nrqbknbr',
  'nrqknbbr',
  'nrqknrbb',
  'bbnrkqnr',
  'bnrbkqnr',
  'bnrkqbnr',
  'bnrkqnrb',
  'nbbrkqnr',
  'nrbbkqnr',
  'nrbkqbnr',
  'nrbkqnrb',
  'nbrkbqnr',
  'nrkbbqnr',
  'nrkqbbnr',
  'nrkqbnrb',
  'nbrkqnbr',
  'nrkbqnbr',
  'nrkqnbbr',
  'nrkqnrbb',
  'bbnrknqr',
  'bnrbknqr',
  'bnrknbqr',
  'bnrknqrb',
  'nbbrknqr',
  'nrbbknqr',
  'nrbknbqr',
  'nrbknqrb',
  'nbrkbnqr',
  'nrkbbnqr',
  'nrknbbqr',
  'nrknbqrb',
  'nbrknqbr',
  'nrkbnqbr',
  'nrknqbbr',
  'nrknqrbb',
  'bbnrknrq',
  'bnrbknrq',
  'bnrknbrq',
  'bnrknrqb',
  'nbbrknrq',
  'nrbbknrq',
  'nrbknbrq',
  'nrbknrqb',
  'nbrkbnrq',
  'nrkbbnrq',
  'nrknbbrq',
  'nrknbrqb',
  'nbrknrbq',
  'nrkbnrbq',
  'nrknrbbq',
  'nrknrqbb',
  'bbqnrkrn',
  'bqnbrkrn',
  'bqnrkbrn',
  'bqnrkrnb',
  'qbbnrkrn',
  'qnbbrkrn',
  'qnbrkbrn',
  'qnbrkrnb',
  'qbnrbkrn',
  'qnrbbkrn',
  'qnrkbbrn',
  'qnrkbrnb',
  'qbnrkrbn',
  'qnrbkrbn',
  'qnrkrbbn',
  'qnrkrnbb',
  'bbnqrkrn',
  'bnqbrkrn',
  'bnqrkbrn',
  'bnqrkrnb',
  'nbbqrkrn',
  'nqbbrkrn',
  'nqbrkbrn',
  'nqbrkrnb',
  'nbqrbkrn',
  'nqrbbkrn',
  'nqrkbbrn',
  'nqrkbrnb',
  'nbqrkrbn',
  'nqrbkrbn',
  'nqrkrbbn',
  'nqrkrnbb',
  'bbnrqkrn',
  'bnrbqkrn',
  'bnrqkbrn',
  'bnrqkrnb',
  'nbbrqkrn',
  'nrbbqkrn',
  'nrbqkbrn',
  'nrbqkrnb',
  'nbrqbkrn',
  'nrqbbkrn',
  'nrqkbbrn',
  'nrqkbrnb',
  'nbrqkrbn',
  'nrqbkrbn',
  'nrqkrbbn',
  'nrqkrnbb',
  'bbnrkqrn',
  'bnrbkqrn',
  'bnrkqbrn',
  'bnrkqrnb',
  'nbbrkqrn',
  'nrbbkqrn',
  'nrbkqbrn',
  'nrbkqrnb',
  'nbrkbqrn',
  'nrkbbqrn',
  'nrkqbbrn',
  'nrkqbrnb',
  'nbrkqrbn',
  'nrkbqrbn',
  'nrkqrbbn',
  'nrkqrnbb',
  'bbnrkrqn',
  'bnrbkrqn',
  'bnrkrbqn',
  'bnrkrqnb',
  'nbbrkrqn',
  'nrbbkrqn',
  'nrbkrbqn',
  'nrbkrqnb',
  'nbrkbrqn',
  'nrkbbrqn',
  'nrkrbbqn',
  'nrkrbqnb',
  'nbrkrqbn',
  'nrkbrqbn',
  'nrkrqbbn',
  'nrkrqnbb',
  'bbnrkrnq',
  'bnrbkrnq',
  'bnrkrbnq',
  'bnrkrnqb',
  'nbbrkrnq',
  'nrbbkrnq',
  'nrbkrbnq',
  'nrbkrnqb',
  'nbrkbrnq',
  'nrkbbrnq',
  'nrkrbbnq',
  'nrkrbnqb',
  'nbrkrnbq',
  'nrkbrnbq',
  'nrkrnbbq',
  'nrkrnqbb',
  'bbqrnnkr',
  'bqrbnnkr',
  'bqrnnbkr',
  'bqrnnkrb',
  'qbbrnnkr',
  'qrbbnnkr',
  'qrbnnbkr',
  'qrbnnkrb',
  'qbrnbnkr',
  'qrnbbnkr',
  'qrnnbbkr',
  'qrnnbkrb',
  'qbrnnkbr',
  'qrnbnkbr',
  'qrnnkbbr',
  'qrnnkrbb',
  'bbrqnnkr',
  'brqbnnkr',
  'brqnnbkr',
  'brqnnkrb',
  'rbbqnnkr',
  'rqbbnnkr',
  'rqbnnbkr',
  'rqbnnkrb',
  'rbqnbnkr',
  'rqnbbnkr',
  'rqnnbbkr',
  'rqnnbkrb',
  'rbqnnkbr',
  'rqnbnkbr',
  'rqnnkbbr',
  'rqnnkrbb',
  'bbrnqnkr',
  'brnbqnkr',
  'brnqnbkr',
  'brnqnkrb',
  'rbbnqnkr',
  'rnbbqnkr',
  'rnbqnbkr',
  'rnbqnkrb',
  'rbnqbnkr',
  'rnqbbnkr',
  'rnqnbbkr',
  'rnqnbkrb',
  'rbnqnkbr',
  'rnqbnkbr',
  'rnqnkbbr',
  'rnqnkrbb',
  'bbrnnqkr',
  'brnbnqkr',
  'brnnqbkr',
  'brnnqkrb',
  'rbbnnqkr',
  'rnbbnqkr',
  'rnbnqbkr',
  'rnbnqkrb',
  'rbnnbqkr',
  'rnnbbqkr',
  'rnnqbbkr',
  'rnnqbkrb',
  'rbnnqkbr',
  'rnnbqkbr',
  'rnnqkbbr',
  'rnnqkrbb',
  'bbrnnkqr',
  'brnbnkqr',
  'brnnkbqr',
  'brnnkqrb',
  'rbbnnkqr',
  'rnbbnkqr',
  'rnbnkbqr',
  'rnbnkqrb',
  'rbnnbkqr',
  'rnnbbkqr',
  'rnnkbbqr',
  'rnnkbqrb',
  'rbnnkqbr',
  'rnnbkqbr',
  'rnnkqbbr',
  'rnnkqrbb',
  'bbrnnkrq',
  'brnbnkrq',
  'brnnkbrq',
  'brnnkrqb',
  'rbbnnkrq',
  'rnbbnkrq',
  'rnbnkbrq',
  'rnbnkrqb',
  'rbnnbkrq',
  'rnnbbkrq',
  'rnnkbbrq',
  'rnnkbrqb',
  'rbnnkrbq',
  'rnnbkrbq',
  'rnnkrbbq',
  'rnnkrqbb',
  'bbqrnknr',
  'bqrbnknr',
  'bqrnkbnr',
  'bqrnknrb',
  'qbbrnknr',
  'qrbbnknr',
  'qrbnkbnr',
  'qrbnknrb',
  'qbrnbknr',
  'qrnbbknr',
  'qrnkbbnr',
  'qrnkbnrb',
  'qbrnknbr',
  'qrnbknbr',
  'qrnknbbr',
  'qrnknrbb',
  'bbrqnknr',
  'brqbnknr',
  'brqnkbnr',
  'brqnknrb',
  'rbbqnknr',
  'rqbbnknr',
  'rqbnkbnr',
  'rqbnknrb',
  'rbqnbknr',
  'rqnbbknr',
  'rqnkbbnr',
  'rqnkbnrb',
  'rbqnknbr',
  'rqnbknbr',
  'rqnknbbr',
  'rqnknrbb',
  'bbrnqknr',
  'brnbqknr',
  'brnqkbnr',
  'brnqknrb',
  'rbbnqknr',
  'rnbbqknr',
  'rnbqkbnr',
  'rnbqknrb',
  'rbnqbknr',
  'rnqbbknr',
  'rnqkbbnr',
  'rnqkbnrb',
  'rbnqknbr',
  'rnqbknbr',
  'rnqknbbr',
  'rnqknrbb',
  'bbrnkqnr',
  'brnbkqnr',
  'brnkqbnr',
  'brnkqnrb',
  'rbbnkqnr',
  'rnbbkqnr',
  'rnbkqbnr',
  'rnbkqnrb',
  'rbnkbqnr',
  'rnkbbqnr',
  'rnkqbbnr',
  'rnkqbnrb',
  'rbnkqnbr',
  'rnkbqnbr',
  'rnkqnbbr',
  'rnkqnrbb',
  'bbrnknqr',
  'brnbknqr',
  'brnknbqr',
  'brnknqrb',
  'rbbnknqr',
  'rnbbknqr',
  'rnbknbqr',
  'rnbknqrb',
  'rbnkbnqr',
  'rnkbbnqr',
  'rnknbbqr',
  'rnknbqrb',
  'rbnknqbr',
  'rnkbnqbr',
  'rnknqbbr',
  'rnknqrbb',
  'bbrnknrq',
  'brnbknrq',
  'brnknbrq',
  'brnknrqb',
  'rbbnknrq',
  'rnbbknrq',
  'rnbknbrq',
  'rnbknrqb',
  'rbnkbnrq',
  'rnkbbnrq',
  'rnknbbrq',
  'rnknbrqb',
  'rbnknrbq',
  'rnkbnrbq',
  'rnknrbbq',
  'rnknrqbb',
  'bbqrnkrn',
  'bqrbnkrn',
  'bqrnkbrn',
  'bqrnkrnb',
  'qbbrnkrn',
  'qrbbnkrn',
  'qrbnkbrn',
  'qrbnkrnb',
  'qbrnbkrn',
  'qrnbbkrn',
  'qrnkbbrn',
  'qrnkbrnb',
  'qbrnkrbn',
  'qrnbkrbn',
  'qrnkrbbn',
  'qrnkrnbb',
  'bbrqnkrn',
  'brqbnkrn',
  'brqnkbrn',
  'brqnkrnb',
  'rbbqnkrn',
  'rqbbnkrn',
  'rqbnkbrn',
  'rqbnkrnb',
  'rbqnbkrn',
  'rqnbbkrn',
  'rqnkbbrn',
  'rqnkbrnb',
  'rbqnkrbn',
  'rqnbkrbn',
  'rqnkrbbn',
  'rqnkrnbb',
  'bbrnqkrn',
  'brnbqkrn',
  'brnqkbrn',
  'brnqkrnb',
  'rbbnqkrn',
  'rnbbqkrn',
  'rnbqkbrn',
  'rnbqkrnb',
  'rbnqbkrn',
  'rnqbbkrn',
  'rnqkbbrn',
  'rnqkbrnb',
  'rbnqkrbn',
  'rnqbkrbn',
  'rnqkrbbn',
  'rnqkrnbb',
  'bbrnkqrn',
  'brnbkqrn',
  'brnkqbrn',
  'brnkqrnb',
  'rbbnkqrn',
  'rnbbkqrn',
  'rnbkqbrn',
  'rnbkqrnb',
  'rbnkbqrn',
  'rnkbbqrn',
  'rnkqbbrn',
  'rnkqbrnb',
  'rbnkqrbn',
  'rnkbqrbn',
  'rnkqrbbn',
  'rnkqrnbb',
  'bbrnkrqn',
  'brnbkrqn',
  'brnkrbqn',
  'brnkrqnb',
  'rbbnkrqn',
  'rnbbkrqn',
  'rnbkrbqn',
  'rnbkrqnb',
  'rbnkbrqn',
  'rnkbbrqn',
  'rnkrbbqn',
  'rnkrbqnb',
  'rbnkrqbn',
  'rnkbrqbn',
  'rnkrqbbn',
  'rnkrqnbb',
  'bbrnkrnq',
  'brnbkrnq',
  'brnkrbnq',
  'brnkrnqb',
  'rbbnkrnq',
  'rnbbkrnq',
  'rnbkrbnq',
  'rnbkrnqb',
  'rbnkbrnq',
  'rnkbbrnq',
  'rnkrbbnq',
  'rnkrbnqb',
  'rbnkrnbq',
  'rnkbrnbq',
  'rnkrnbbq',
  'rnkrnqbb',
  'bbqrknnr',
  'bqrbknnr',
  'bqrknbnr',
  'bqrknnrb',
  'qbbrknnr',
  'qrbbknnr',
  'qrbknbnr',
  'qrbknnrb',
  'qbrkbnnr',
  'qrkbbnnr',
  'qrknbbnr',
  'qrknbnrb',
  'qbrknnbr',
  'qrkbnnbr',
  'qrknnbbr',
  'qrknnrbb',
  'bbrqknnr',
  'brqbknnr',
  'brqknbnr',
  'brqknnrb',
  'rbbqknnr',
  'rqbbknnr',
  'rqbknbnr',
  'rqbknnrb',
  'rbqkbnnr',
  'rqkbbnnr',
  'rqknbbnr',
  'rqknbnrb',
  'rbqknnbr',
  'rqkbnnbr',
  'rqknnbbr',
  'rqknnrbb',
  'bbrkqnnr',
  'brkbqnnr',
  'brkqnbnr',
  'brkqnnrb',
  'rbbkqnnr',
  'rkbbqnnr',
  'rkbqnbnr',
  'rkbqnnrb',
  'rbkqbnnr',
  'rkqbbnnr',
  'rkqnbbnr',
  'rkqnbnrb',
  'rbkqnnbr',
  'rkqbnnbr',
  'rkqnnbbr',
  'rkqnnrbb',
  'bbrknqnr',
  'brkbnqnr',
  'brknqbnr',
  'brknqnrb',
  'rbbknqnr',
  'rkbbnqnr',
  'rkbnqbnr',
  'rkbnqnrb',
  'rbknbqnr',
  'rknbbqnr',
  'rknqbbnr',
  'rknqbnrb',
  'rbknqnbr',
  'rknbqnbr',
  'rknqnbbr',
  'rknqnrbb',
  'bbrknnqr',
  'brkbnnqr',
  'brknnbqr',
  'brknnqrb',
  'rbbknnqr',
  'rkbbnnqr',
  'rkbnnbqr',
  'rkbnnqrb',
  'rbknbnqr',
  'rknbbnqr',
  'rknnbbqr',
  'rknnbqrb',
  'rbknnqbr',
  'rknbnqbr',
  'rknnqbbr',
  'rknnqrbb',
  'bbrknnrq',
  'brkbnnrq',
  'brknnbrq',
  'brknnrqb',
  'rbbknnrq',
  'rkbbnnrq',
  'rkbnnbrq',
  'rkbnnrqb',
  'rbknbnrq',
  'rknbbnrq',
  'rknnbbrq',
  'rknnbrqb',
  'rbknnrbq',
  'rknbnrbq',
  'rknnrbbq',
  'rknnrqbb',
  'bbqrknrn',
  'bqrbknrn',
  'bqrknbrn',
  'bqrknrnb',
  'qbbrknrn',
  'qrbbknrn',
  'qrbknbrn',
  'qrbknrnb',
  'qbrkbnrn',
  'qrkbbnrn',
  'qrknbbrn',
  'qrknbrnb',
  'qbrknrbn',
  'qrkbnrbn',
  'qrknrbbn',
  'qrknrnbb',
  'bbrqknrn',
  'brqbknrn',
  'brqknbrn',
  'brqknrnb',
  'rbbqknrn',
  'rqbbknrn',
  'rqbknbrn',
  'rqbknrnb',
  'rbqkbnrn',
  'rqkbbnrn',
  'rqknbbrn',
  'rqknbrnb',
  'rbqknrbn',
  'rqkbnrbn',
  'rqknrbbn',
  'rqknrnbb',
  'bbrkqnrn',
  'brkbqnrn',
  'brkqnbrn',
  'brkqnrnb',
  'rbbkqnrn',
  'rkbbqnrn',
  'rkbqnbrn',
  'rkbqnrnb',
  'rbkqbnrn',
  'rkqbbnrn',
  'rkqnbbrn',
  'rkqnbrnb',
  'rbkqnrbn',
  'rkqbnrbn',
  'rkqnrbbn',
  'rkqnrnbb',
  'bbrknqrn',
  'brkbnqrn',
  'brknqbrn',
  'brknqrnb',
  'rbbknqrn',
  'rkbbnqrn',
  'rkbnqbrn',
  'rkbnqrnb',
  'rbknbqrn',
  'rknbbqrn',
  'rknqbbrn',
  'rknqbrnb',
  'rbknqrbn',
  'rknbqrbn',
  'rknqrbbn',
  'rknqrnbb',
  'bbrknrqn',
  'brkbnrqn',
  'brknrbqn',
  'brknrqnb',
  'rbbknrqn',
  'rkbbnrqn',
  'rkbnrbqn',
  'rkbnrqnb',
  'rbknbrqn',
  'rknbbrqn',
  'rknrbbqn',
  'rknrbqnb',
  'rbknrqbn',
  'rknbrqbn',
  'rknrqbbn',
  'rknrqnbb',
  'bbrknrnq',
  'brkbnrnq',
  'brknrbnq',
  'brknrnqb',
  'rbbknrnq',
  'rkbbnrnq',
  'rkbnrbnq',
  'rkbnrnqb',
  'rbknbrnq',
  'rknbbrnq',
  'rknrbbnq',
  'rknrbnqb',
  'rbknrnbq',
  'rknbrnbq',
  'rknrnbbq',
  'rknrnqbb',
  'bbqrkrnn',
  'bqrbkrnn',
  'bqrkrbnn',
  'bqrkrnnb',
  'qbbrkrnn',
  'qrbbkrnn',
  'qrbkrbnn',
  'qrbkrnnb',
  'qbrkbrnn',
  'qrkbbrnn',
  'qrkrbbnn',
  'qrkrbnnb',
  'qbrkrnbn',
  'qrkbrnbn',
  'qrkrnbbn',
  'qrkrnnbb',
  'bbrqkrnn',
  'brqbkrnn',
  'brqkrbnn',
  'brqkrnnb',
  'rbbqkrnn',
  'rqbbkrnn',
  'rqbkrbnn',
  'rqbkrnnb',
  'rbqkbrnn',
  'rqkbbrnn',
  'rqkrbbnn',
  'rqkrbnnb',
  'rbqkrnbn',
  'rqkbrnbn',
  'rqkrnbbn',
  'rqkrnnbb',
  'bbrkqrnn',
  'brkbqrnn',
  'brkqrbnn',
  'brkqrnnb',
  'rbbkqrnn',
  'rkbbqrnn',
  'rkbqrbnn',
  'rkbqrnnb',
  'rbkqbrnn',
  'rkqbbrnn',
  'rkqrbbnn',
  'rkqrbnnb',
  'rbkqrnbn',
  'rkqbrnbn',
  'rkqrnbbn',
  'rkqrnnbb',
  'bbrkrqnn',
  'brkbrqnn',
  'brkrqbnn',
  'brkrqnnb',
  'rbbkrqnn',
  'rkbbrqnn',
  'rkbrqbnn',
  'rkbrqnnb',
  'rbkrbqnn',
  'rkrbbqnn',
  'rkrqbbnn',
  'rkrqbnnb',
  'rbkrqnbn',
  'rkrbqnbn',
  'rkrqnbbn',
  'rkrqnnbb',
  'bbrkrnqn',
  'brkbrnqn',
  'brkrnbqn',
  'brkrnqnb',
  'rbbkrnqn',
  'rkbbrnqn',
  'rkbrnbqn',
  'rkbrnqnb',
  'rbkrbnqn',
  'rkrbbnqn',
  'rkrnbbqn',
  'rkrnbqnb',
  'rbkrnqbn',
  'rkrbnqbn',
  'rkrnqbbn',
  'rkrnqnbb',
  'bbrkrnnq',
  'brkbrnnq',
  'brkrnbnq',
  'brkrnnqb',
  'rbbkrnnq',
  'rkbbrnnq',
  'rkbrnbnq',
  'rkbrnnqb',
  'rbkrbnnq',
  'rkrbbnnq',
  'rkrnbbnq',
  'rkrnbnqb',
  'rbkrnnbq',
  'rkrbnnbq',
  'rkrnnbbq',
  'rkrnnqbb',
];

export const extendMainline = <T>(game: ChessGame<T>, data: T[]) => {
  let node = game.moves;
  while (node.children.length) {
    const child = node.children[0];
    node = child;
  }
  data.forEach(d => {
    const newNode = new ChildNode(d);
    node.children = [newNode];
    node = newNode;
  });
};

export function gameToPgn(
  pairing: Pairing,
  boardIndex: number,
  tournament: Tournament,
  permitIllegalMoves: boolean | undefined,

  round: number,
  game: Game,
): string {
  const headers = new Map<string, string>();
  headers.set('Event', tournament.name);
  headers.set('White', getPlayerName(pairing.white));
  headers.set('Black', getPlayerName(pairing.black));
  if (tournament.chess960 == 'ANY') {
    // seems to be the way to check if it's a chess960 game
    headers.set('FEN', positionToFen(game.chess960)!);
  }
  if (pairing.white.title) {
    headers.set('WhiteTitle', pairing.white.title);
  }
  if (pairing.black.title) {
    headers.set('BlackTitle', pairing.black.title);
  }
  if (pairing.white.fideid) {
    headers.set('WhiteFideId', `${pairing.white.fideid}`);
  }
  if (pairing.black.fideid) {
    headers.set('BlackFideId', `${pairing.black.fideid}`);
  }
  headers.set('Result', pairing.result);
  // This field isn't necessarily in PGN format and can hold any random gibberish string as well
  // In case this does not contain the correct data, we can replace it using addReplacement command
  if (tournament.timecontrol) {
    headers.set('TimeControl', tournament.timecontrol);
  }
  headers.set('Round', `${round}.${boardIndex + 1}`);

  // Build initial position (use chess960 FEN if provided, otherwise standard initial FEN)
  const initialFen =
    tournament.chess960 == 'ANY'
      ? positionToFen(game.chess960)!
      : 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
  const setup = parseFen(initialFen).unwrap();
  const pos = Chess.fromSetup(setup).unwrap();

  // Validate moves sequentially, stop at first illegal/unrecognised SAN
  const mainline: Array<{ comments: string[]; san: string }> = [];
  for (const move of game.moves) {
    const [san, timeStringInSecs] = move.split(' ');
    const mv = permitIllegalMoves ? undefined : parseSan(pos, san);
    if (!permitIllegalMoves)
      if (!mv || !pos.isLegal(mv)) break;
    let comments: string[] = [];
    if (timeStringInSecs !== undefined && !timeStringInSecs.startsWith('+')) {
      const time = dayjs.duration(parseInt(timeStringInSecs), 'seconds');
      const hours = time.hours();
      const minutes = time.minutes();
      const seconds = time.seconds();
      comments.push(`[%clk ${hours}:${minutes}:${seconds}]`);
    }
    mainline.push({ comments, san });
    if (!permitIllegalMoves && mv) {
      pos.play(mv);
    }
  }
  const chessGame: ChessGame<PgnNodeData> = {
    headers: headers,
    moves: new Node(),
  };
  extendMainline(chessGame, mainline);
  return makePgn(chessGame);
}

export default async function fetchLcc(id: string, permitIllegalMoves?: boolean): Promise<string> {
  const match = id.match(/^([0-9a-z\-]+)\/([0-9]+)$/);
  if (!match) throw `Invalid lcc URL: ${id}`;
  const tournamentId = match[1];
  const round = parseInt(match[2]);

  const tournament: Tournament = await fetch(
    `https://1.pool.livechesscloud.com/get/${tournamentId}/tournament.json`,
  ).then(res => res.json());
  const roundInfo = await getRound(tournamentId, round);
  const games: Game[] = [];
  // TODO: fetch games  asynchronously
  for (let i = 1; i <= tournament.rounds[round - 1].count; i++) {
    games.push(await getGame(tournamentId, round, i).catch(() => ({ moves: [], chess960: 518 })));
  }
  let pgn = '';
  for (const [boardIndex, game] of games.entries()) {
    const pairing = roundInfo.pairings[boardIndex];
    if (!pairing.white || !pairing.black) continue;
    pgn += gameToPgn(pairing, boardIndex, tournament, permitIllegalMoves, round, game) + '\n\n';
  }
  return pgn;
}

const loop = async (
  roundInfo: components['schemas']['BroadcastRoundInfo'],
  lccId: string,
  loopTimer: number,
  permitIllegalMoves?: boolean
) => {
  while (true) {
    const lccContent = await fetchLcc(lccId, permitIllegalMoves);
    if (lccContent && lccContent !== lastPGN) {
      await pushPGN(roundInfo, lccContent);
      lastPGN = lccContent;
    }
    await sleep(loopTimer * 1000);
  }
};

export const pushLCCCommand = async (args: string[]) => {
  await checkTokenScopes();
  const [roundId, lccId] = args.slice(0, 2);
  // Validate required args
  if (!roundId || !lccId) {
    msgCommonErrorHelp('Round ID and LCC ID are required.');
    exit(1);
  }

  const roundInfo = await getBroadcastRound(roundId);

  if (!roundInfo) {
    console.error(cl.red('Round not found.'));
    exit(1);
  }

  const loopTimer = loopChecker(args);

  const permitIllegalMoves = args.includes('--permit-illegal');

  if (loopTimer) {
    console.log(cl.green(`Starting loop to push PGN every ${cl.whiteBold(loopTimer.toString())} seconds...`));
    console.log(cl.blue('Press Ctrl+C to stop.'));
    await loop(roundInfo, lccId, loopTimer, permitIllegalMoves);
  } else {
    const lccContent = await fetchLcc(lccId, permitIllegalMoves);
    if (lccContent) await pushPGN(roundInfo, lccContent);
  }
};
